"""added iot device setting

Revision ID: fd7030ac4b57
Revises: 19b9821b8116
Create Date: 2024-05-25 00:25:21.177428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7030ac4b57'
down_revision: Union[str, None] = '19b9821b8116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_device_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('setting_name', sa.String(), nullable=True),
    sa.Column('value_str', sa.String(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_device_settings_device_id'), 'iot_device_settings', ['device_id'], unique=False)
    op.create_index(op.f('ix_iot_device_settings_id'), 'iot_device_settings', ['id'], unique=False)
    op.add_column('log_entries', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('log_entries', sa.Column('log_level', sa.String(), nullable=True))
    op.add_column('log_entries', sa.Column('log_stream', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_entries', 'log_stream')
    op.drop_column('log_entries', 'log_level')
    op.drop_column('log_entries', 'device_id')
    op.drop_index(op.f('ix_iot_device_settings_id'), table_name='iot_device_settings')
    op.drop_index(op.f('ix_iot_device_settings_device_id'), table_name='iot_device_settings')
    op.drop_table('iot_device_settings')
    # ### end Alembic commands ###
