apiVersion: v1
kind: Secret
metadata:
  name: hoarder-secrets
type: Opaque
data:
  MEILI_MASTER_KEY: {{ .Values.meilisearch.masterKey | b64enc }}
  OPENAI_API_KEY: {{ .Values.openai.apiKey | b64enc }}