apiVersion: v1
kind: Secret
metadata:
  name: hoarder-secrets
type: Opaque
data:
  MEILI_MASTER_KEY: {{ .Values.meilisearch.masterKey | b64enc }}
  OPENAI_API_KEY: {{ .Values.openai.apiKey | b64enc }}
  NEXTAUTH_SECRET: {{ .Values.nextAuth.secret | b64enc }}
  OAUTH_CLIENT_ID: {{ .Values.oauth.clientId | b64enc }}
  OAUTH_CLIENT_SECRET: {{ .Values.oauth.clientSecret | b64enc }}