{{ if .Values.certVerify.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials
  namespace: cert-manager
type: Opaque
stringData:
  secret-access-key: {{ .Values.certVerify.awsSecretAccessKey }}

---
# Then create the ClusterIssuer using DNS-01 challenge
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: {{ .Values.certVerify.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: us-east-1  # Replace with your AWS region
          accessKeyID: {{ .Values.certVerify.awsAccessKeyId }}
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key
      selector:
        dnsZones:
        - '{{ .Values.domain }}'
{{ end }}