apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials
  namespace: cert-manager
type: Opaque
stringData:
  access-key-id: '{{ .Values.certManager.awsAccessKeyId }}'
  secret-access-key: '{{ .Values.certManager.awsSecretAccessKey }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-credentials
  namespace: cert-manager
type: Opaque
stringData:
  api-token: '{{ .Values.certManager.cloudflareApiToken }}'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: {{ .Values.certVerify.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-aws
    solvers:
    - dns01:
        route53:
          region: us-east-1  # Replace with your AWS region
          accessKeyIDSecretRef:
            name: route53-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key
      selector:
        dnsZones:
        - 'court306.com'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-aws
spec:
  acme:
    email: {{ .Values.certVerify.email }}
    # staging url
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-aws
    solvers:
    - dns01:
        route53:
          region: us-east-1  # Replace with your AWS region
          accessKeyIDSecretRef:
            name: route53-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key
      selector:
        dnsZones:
        - 'court306.com'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-cloudflare
spec:
  acme:
    email: {{ .Values.certVerify.email }}
    # staging url
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-cloudflare
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-dns-credentials
            key: api-token
      selector:
        dnsZones:
        - 'cthon.io'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cloudflare
spec:
  acme:
    email: {{ .Values.certVerify.email }}
    # staging url
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-cloudflare
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-dns-credentials
            key: api-token
      selector:
        dnsZones:
        - 'cthon.io'
